<a href="https://colab.research.google.com/github/Hemant10HM/ANNDL-LAB_24mcs004/blob/main/ANN_LAB_4_MLP_Optimizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Optimizers effect on Classification Model

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [2]:
# Define dataset path
dataset_path = "/content/drive/MyDrive/data/WineQT.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.drop('Id', axis=1, inplace=True)

In [5]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [6]:
# Craeting binary classification target
df['Good'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

In [7]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [8]:
X = df.drop(['quality', 'Good'], axis=1)

In [9]:
# Scale features
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [10]:
# Round scaled features
X_scaled = X_scaled.round(2)

In [11]:

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [12]:
X_bin = X_scaled.copy()
y_bin = df['Good']

In [13]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X_bin,y_bin,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (765, 11)
X_test shape :  (378, 11)
y_train shape :  (765,)
y_test shape :  (378,)

In [14]:

# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 11))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [15]:
# 1. We are using adam optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - BinaryAccuracy: 0.8416 - loss: 0.6010
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8493 - loss: 0.4453
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8434 - loss: 0.4288
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8659 - loss: 0.3760
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8532 - loss: 0.3692
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8549 - loss: 0.3529
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8580 - loss: 0.3207
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8653 - loss: 0.3096
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8693 - loss: 0.2978
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8479 - loss: 0.3143
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8731 - loss: 0.2974
Epoch 12/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8747 - loss: 0.2861
Epoch 13/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8801 - loss: 0.2725
Epoch 14/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8672 - loss: 0.2869
Epoch 15/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8465 - loss: 0.3248
Epoch 16/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8763 - loss: 0.2862
Epoch 17/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8728 - loss: 0.2842
Epoch 18/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8876 - loss: 0.2661
Epoch 19/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8802 - loss: 0.2818
Epoch 20/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9011 - loss: 0.2427
Epoch 21/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8773 - loss: 0.2901
Epoch 22/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8691 - loss: 0.2949
Epoch 23/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8953 - loss: 0.2870
Epoch 24/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8703 - loss: 0.2866
Epoch 25/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8850 - loss: 0.2487
Epoch 26/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8855 - loss: 0.2560
Epoch 27/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8777 - loss: 0.2795
Epoch 28/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8637 - loss: 0.3176
Epoch 29/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8730 - loss: 0.3350
Epoch 30/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8760 - loss: 0.2752
Epoch 31/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8765 - loss: 0.2940
Epoch 32/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8799 - loss: 0.2905
Epoch 33/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8887 - loss: 0.2488
Epoch 34/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8980 - loss: 0.2699
Epoch 35/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9006 - loss: 0.2340
Epoch 36/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8673 - loss: 0.2845
Epoch 37/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8927 - loss: 0.2628
Epoch 38/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8893 - loss: 0.2566
Epoch 39/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8870 - loss: 0.2792
Epoch 40/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8764 - loss: 0.2738
Epoch 41/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8904 - loss: 0.2597
Epoch 42/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8885 - loss: 0.2613
Epoch 43/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8782 - loss: 0.2578
Epoch 44/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8951 - loss: 0.2412
Epoch 45/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8825 - loss: 0.2599
Epoch 46/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8881 - loss: 0.2520
Epoch 47/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8925 - loss: 0.2498
Epoch 48/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8920 - loss: 0.2573
Epoch 49/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8840 - loss: 0.2607
Epoch 50/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8996 - loss: 0.2408
Epoch 51/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8830 - loss: 0.2791
Epoch 52/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9002 - loss: 0.2383
Epoch 53/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8670 - loss: 0.2729
Epoch 54/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9084 - loss: 0.2363
Epoch 55/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8684 - loss: 0.2719
Epoch 56/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8920 - loss: 0.2589
Epoch 57/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9026 - loss: 0.2431
Epoch 58/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8922 - loss: 0.2664
Epoch 59/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9114 - loss: 0.2084
Epoch 60/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8984 - loss: 0.2493
Epoch 61/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8923 - loss: 0.2316
Epoch 62/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8901 - loss: 0.2474
Epoch 63/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8852 - loss: 0.2540
Epoch 64/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9002 - loss: 0.2326
Epoch 65/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8893 - loss: 0.2427
Epoch 66/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8942 - loss: 0.2535
Epoch 67/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8867 - loss: 0.2304
Epoch 68/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9075 - loss: 0.2360
Epoch 69/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8966 - loss: 0.2318
Epoch 70/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8951 - loss: 0.2479
Epoch 71/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8823 - loss: 0.2477
Epoch 72/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9021 - loss: 0.2396
Epoch 73/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8937 - loss: 0.2320
Epoch 74/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8741 - loss: 0.2915
Epoch 75/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9006 - loss: 0.2236
Epoch 76/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8915 - loss: 0.2297
Epoch 77/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8864 - loss: 0.2497
Epoch 78/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9131 - loss: 0.2313
Epoch 79/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9040 - loss: 0.2424
Epoch 80/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8854 - loss: 0.2796
Epoch 81/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9062 - loss: 0.2216
Epoch 82/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8849 - loss: 0.2548
Epoch 83/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8937 - loss: 0.2322
Epoch 84/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8906 - loss: 0.2365
Epoch 85/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8882 - loss: 0.2458
Epoch 86/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9049 - loss: 0.2302
Epoch 87/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9029 - loss: 0.2356
Epoch 88/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8855 - loss: 0.2437
Epoch 89/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8940 - loss: 0.2412
Epoch 90/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8858 - loss: 0.2386
Epoch 91/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8974 - loss: 0.2415
Epoch 92/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8885 - loss: 0.2411
Epoch 93/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8952 - loss: 0.2517
Epoch 94/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9166 - loss: 0.2133
Epoch 95/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8954 - loss: 0.2224
Epoch 96/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9034 - loss: 0.2510
Epoch 97/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8923 - loss: 0.2346
Epoch 98/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9049 - loss: 0.2276
Epoch 99/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9115 - loss: 0.2121
Epoch 100/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9123 - loss: 0.2441
Epoch 101/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9002 - loss: 0.2297
Epoch 102/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8759 - loss: 0.2452
Epoch 103/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9003 - loss: 0.2133
Epoch 104/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9168 - loss: 0.2165
Epoch 105/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8997 - loss: 0.2385
Epoch 106/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9004 - loss: 0.2115
Epoch 107/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9093 - loss: 0.2167
Epoch 108/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8969 - loss: 0.2302
Epoch 109/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9055 - loss: 0.2164
Epoch 110/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9035 - loss: 0.2241
Epoch 111/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9125 - loss: 0.1977
Epoch 112/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9005 - loss: 0.2364
Epoch 113/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9106 - loss: 0.2100
Epoch 114/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9187 - loss: 0.2059
Epoch 115/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9232 - loss: 0.1888
Epoch 116/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9063 - loss: 0.2277
Epoch 117/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9020 - loss: 0.2279
Epoch 118/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9170 - loss: 0.2091
Epoch 119/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9156 - loss: 0.2135
Epoch 120/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9129 - loss: 0.2113
Epoch 121/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9108 - loss: 0.2053
Epoch 122/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9072 - loss: 0.2231
Epoch 123/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9217 - loss: 0.2074
Epoch 124/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9091 - loss: 0.2208
Epoch 125/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9231 - loss: 0.1982
Epoch 126/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9140 - loss: 0.1964
Epoch 127/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9246 - loss: 0.1990
Epoch 128/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9057 - loss: 0.2262
Epoch 129/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9131 - loss: 0.2195
Epoch 130/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9245 - loss: 0.1918
Epoch 131/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9201 - loss: 0.2152
Epoch 132/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9164 - loss: 0.2042
Epoch 133/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8982 - loss: 0.2269
Epoch 134/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9091 - loss: 0.2013
Epoch 135/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9235 - loss: 0.1864
Epoch 136/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9093 - loss: 0.2226
Epoch 137/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9237 - loss: 0.2009
Epoch 138/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9177 - loss: 0.2139
Epoch 139/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9210 - loss: 0.2074
Epoch 140/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9147 - loss: 0.2086
Epoch 141/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9002 - loss: 0.2382
Epoch 142/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9038 - loss: 0.2178
Epoch 143/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9239 - loss: 0.2008
Epoch 144/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9279 - loss: 0.2011
Epoch 145/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9257 - loss: 0.1988
Epoch 146/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9280 - loss: 0.1732
Epoch 147/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9082 - loss: 0.2079
Epoch 148/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9127 - loss: 0.2121
Epoch 149/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9301 - loss: 0.1793
Epoch 150/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9294 - loss: 0.1734
Epoch 151/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9277 - loss: 0.1852
Epoch 152/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9031 - loss: 0.2160
Epoch 153/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9347 - loss: 0.1854
Epoch 154/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9233 - loss: 0.1874
Epoch 155/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9349 - loss: 0.1833
Epoch 156/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9226 - loss: 0.2053
Epoch 157/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9254 - loss: 0.2061
Epoch 158/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9228 - loss: 0.1906
Epoch 159/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9121 - loss: 0.1889
Epoch 160/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9232 - loss: 0.2031
Epoch 161/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9246 - loss: 0.2188
Epoch 162/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9306 - loss: 0.1865
Epoch 163/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9406 - loss: 0.1812
Epoch 164/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9355 - loss: 0.1969
Epoch 165/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9214 - loss: 0.2083
Epoch 166/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9213 - loss: 0.1849
Epoch 167/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9215 - loss: 0.1759
Epoch 168/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9081 - loss: 0.1996
Epoch 169/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9243 - loss: 0.1781
Epoch 170/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9281 - loss: 0.1869
Epoch 171/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9280 - loss: 0.1844
Epoch 172/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9289 - loss: 0.1810
Epoch 173/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9164 - loss: 0.2034
Epoch 174/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9372 - loss: 0.1789
Epoch 175/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9399 - loss: 0.1789
Epoch 176/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9202 - loss: 0.1965
Epoch 177/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9223 - loss: 0.1851
Epoch 178/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9284 - loss: 0.2109
Epoch 179/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9513 - loss: 0.1487
Epoch 180/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9411 - loss: 0.1593
Epoch 181/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9410 - loss: 0.1672
Epoch 182/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9405 - loss: 0.1698
Epoch 183/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9303 - loss: 0.1706
Epoch 184/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9222 - loss: 0.1871
Epoch 185/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9275 - loss: 0.1809
Epoch 186/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9337 - loss: 0.1865
Epoch 187/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9270 - loss: 0.1718
Epoch 188/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9419 - loss: 0.1743
Epoch 189/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9273 - loss: 0.1786
Epoch 190/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9320 - loss: 0.1881
Epoch 191/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9362 - loss: 0.1730
Epoch 192/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9433 - loss: 0.1560
Epoch 193/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9344 - loss: 0.1691
Epoch 194/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9241 - loss: 0.1869
Epoch 195/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9297 - loss: 0.1864
Epoch 196/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9291 - loss: 0.1680
Epoch 197/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9359 - loss: 0.1807
Epoch 198/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9222 - loss: 0.1976
Epoch 199/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9419 - loss: 0.1659
Epoch 200/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9318 - loss: 0.1749
Epoch 201/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9372 - loss: 0.1688
Epoch 202/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9448 - loss: 0.1655
Epoch 203/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9072 - loss: 0.2064
Epoch 204/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9421 - loss: 0.1639
Epoch 205/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9298 - loss: 0.1742
Epoch 206/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9342 - loss: 0.1803
Epoch 207/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9388 - loss: 0.1603
Epoch 208/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9424 - loss: 0.1554
Epoch 209/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9353 - loss: 0.1736
Epoch 210/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9165 - loss: 0.1859
Epoch 211/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9375 - loss: 0.1662
Epoch 212/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9458 - loss: 0.1571
Epoch 213/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9493 - loss: 0.1548
Epoch 214/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9271 - loss: 0.1559
Epoch 215/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9382 - loss: 0.1633
Epoch 216/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9476 - loss: 0.1477
Epoch 217/250

In [16]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8839 - loss: 0.4162
Testing time: 0.26 seconds

In [17]:

y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step
(378, 1)
(378,)

In [18]:

# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8862433862433863
Confusion Matrix:
 [[316  10]
 [ 33  19]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       326
           1       0.66      0.37      0.47        52

    accuracy                           0.89       378
   macro avg       0.78      0.67      0.70       378
weighted avg       0.87      0.89      0.87       378

In [19]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [20]:
# 2. We are using rmsprop optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='rmsprop', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - BinaryAccuracy: 0.9242 - loss: 0.1751
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9510 - loss: 0.1256
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9556 - loss: 0.1278
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9529 - loss: 0.1249
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9523 - loss: 0.1382
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9360 - loss: 0.1506
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9427 - loss: 0.1413
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9335 - loss: 0.1531
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9397 - loss: 0.1628
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9372 - loss: 0.1460
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9446 - loss: 0.1367
Epoch 12/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9446 - loss: 0.1397
Epoch 13/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9524 - loss: 0.1436
Epoch 14/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9509 - loss: 0.1407
Epoch 15/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9260 - loss: 0.1657
Epoch 16/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9528 - loss: 0.1102
Epoch 17/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9366 - loss: 0.1666
Epoch 18/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9448 - loss: 0.1443
Epoch 19/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9522 - loss: 0.1267
Epoch 20/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9397 - loss: 0.1461
Epoch 21/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9544 - loss: 0.1183
Epoch 22/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9436 - loss: 0.1366
Epoch 23/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9432 - loss: 0.1462
Epoch 24/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9373 - loss: 0.1526
Epoch 25/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9497 - loss: 0.1361
Epoch 26/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9484 - loss: 0.1481
Epoch 27/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9466 - loss: 0.1309
Epoch 28/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9512 - loss: 0.1406
Epoch 29/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9482 - loss: 0.1340
Epoch 30/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9433 - loss: 0.1364
Epoch 31/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9512 - loss: 0.1283
Epoch 32/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9393 - loss: 0.1490
Epoch 33/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9549 - loss: 0.1333
Epoch 34/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9532 - loss: 0.1291
Epoch 35/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9445 - loss: 0.1376
Epoch 36/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9470 - loss: 0.1289
Epoch 37/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9270 - loss: 0.1562
Epoch 38/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9481 - loss: 0.1446
Epoch 39/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9422 - loss: 0.1404
Epoch 40/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9511 - loss: 0.1307
Epoch 41/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9465 - loss: 0.1367
Epoch 42/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9564 - loss: 0.1418
Epoch 43/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9598 - loss: 0.1230
Epoch 44/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9409 - loss: 0.1359
Epoch 45/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9444 - loss: 0.1311
Epoch 46/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9559 - loss: 0.1227
Epoch 47/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9525 - loss: 0.1276
Epoch 48/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9402 - loss: 0.1524
Epoch 49/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9628 - loss: 0.1189
Epoch 50/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9424 - loss: 0.1250
Epoch 51/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9482 - loss: 0.1307
Epoch 52/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9474 - loss: 0.1304
Epoch 53/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9492 - loss: 0.1305
Epoch 54/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9362 - loss: 0.1383
Epoch 55/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9495 - loss: 0.1273
Epoch 56/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9519 - loss: 0.1298
Epoch 57/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9374 - loss: 0.1498
Epoch 58/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9501 - loss: 0.1176
Epoch 59/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9537 - loss: 0.1261
Epoch 60/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9445 - loss: 0.1398
Epoch 61/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9566 - loss: 0.1232
Epoch 62/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9490 - loss: 0.1299
Epoch 63/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9545 - loss: 0.1221
Epoch 64/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9433 - loss: 0.1458
Epoch 65/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9408 - loss: 0.1423
Epoch 66/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9551 - loss: 0.1271
Epoch 67/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9624 - loss: 0.1195
Epoch 68/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9524 - loss: 0.1158
Epoch 69/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9513 - loss: 0.1351
Epoch 70/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9557 - loss: 0.1186
Epoch 71/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9366 - loss: 0.1349
Epoch 72/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9479 - loss: 0.1351
Epoch 73/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9443 - loss: 0.1345
Epoch 74/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9381 - loss: 0.1460
Epoch 75/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9456 - loss: 0.1138
Epoch 76/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9619 - loss: 0.1078
Epoch 77/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9526 - loss: 0.1187
Epoch 78/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9488 - loss: 0.1307
Epoch 79/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9513 - loss: 0.1360
Epoch 80/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9598 - loss: 0.1027
Epoch 81/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9459 - loss: 0.1389
Epoch 82/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9544 - loss: 0.1250
Epoch 83/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9696 - loss: 0.0988
Epoch 84/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9451 - loss: 0.1341
Epoch 85/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9603 - loss: 0.0946
Epoch 86/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9499 - loss: 0.1332
Epoch 87/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9648 - loss: 0.0913
Epoch 88/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9489 - loss: 0.1318
Epoch 89/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9420 - loss: 0.1321
Epoch 90/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9485 - loss: 0.1258
Epoch 91/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9517 - loss: 0.1133
Epoch 92/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9538 - loss: 0.1140
Epoch 93/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9615 - loss: 0.1079
Epoch 94/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9606 - loss: 0.1098
Epoch 95/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9462 - loss: 0.1180
Epoch 96/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9503 - loss: 0.1202
Epoch 97/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9610 - loss: 0.1018
Epoch 98/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9545 - loss: 0.1068
Epoch 99/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9580 - loss: 0.0996
Epoch 100/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9443 - loss: 0.1205
Epoch 101/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9514 - loss: 0.1136
Epoch 102/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9603 - loss: 0.1088
Epoch 103/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9540 - loss: 0.1133
Epoch 104/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9607 - loss: 0.1056
Epoch 105/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9537 - loss: 0.1025
Epoch 106/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9651 - loss: 0.0986
Epoch 107/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9528 - loss: 0.1012
Epoch 108/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9687 - loss: 0.0880
Epoch 109/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9581 - loss: 0.1114
Epoch 110/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9544 - loss: 0.1144
Epoch 111/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9622 - loss: 0.0994
Epoch 112/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9520 - loss: 0.1151
Epoch 113/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9432 - loss: 0.1189
Epoch 114/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9497 - loss: 0.1235
Epoch 115/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9520 - loss: 0.1142
Epoch 116/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9600 - loss: 0.0974
Epoch 117/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9501 - loss: 0.1291
Epoch 118/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9502 - loss: 0.1270
Epoch 119/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9802 - loss: 0.0725
Epoch 120/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9504 - loss: 0.1190
Epoch 121/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9601 - loss: 0.0982
Epoch 122/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9482 - loss: 0.1182
Epoch 123/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9538 - loss: 0.1096
Epoch 124/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9678 - loss: 0.0988
Epoch 125/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9462 - loss: 0.1292
Epoch 126/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9452 - loss: 0.1096
Epoch 127/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9511 - loss: 0.1032
Epoch 128/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9489 - loss: 0.1223
Epoch 129/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9668 - loss: 0.0892
Epoch 130/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9508 - loss: 0.1009
Epoch 131/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9670 - loss: 0.0858
Epoch 132/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9400 - loss: 0.1192
Epoch 133/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9642 - loss: 0.1010
Epoch 134/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9640 - loss: 0.0911
Epoch 135/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9480 - loss: 0.1148
Epoch 136/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9622 - loss: 0.0890
Epoch 137/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9635 - loss: 0.0943
Epoch 138/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9616 - loss: 0.1016
Epoch 139/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9583 - loss: 0.0978
Epoch 140/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9582 - loss: 0.1025
Epoch 141/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9758 - loss: 0.0872
Epoch 142/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9534 - loss: 0.1009
Epoch 143/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9698 - loss: 0.0951
Epoch 144/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9522 - loss: 0.1031
Epoch 145/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9565 - loss: 0.1020
Epoch 146/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9583 - loss: 0.0989
Epoch 147/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9651 - loss: 0.0878
Epoch 148/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9524 - loss: 0.1178
Epoch 149/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9698 - loss: 0.0797
Epoch 150/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9710 - loss: 0.0853
Epoch 151/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9425 - loss: 0.1240
Epoch 152/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9517 - loss: 0.1046
Epoch 153/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9523 - loss: 0.1128
Epoch 154/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9534 - loss: 0.1056
Epoch 155/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9590 - loss: 0.1057
Epoch 156/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9522 - loss: 0.1023
Epoch 157/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9655 - loss: 0.0985
Epoch 158/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9546 - loss: 0.1039
Epoch 159/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9499 - loss: 0.1086
Epoch 160/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9651 - loss: 0.0819
Epoch 161/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9529 - loss: 0.1148
Epoch 162/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9580 - loss: 0.0911
Epoch 163/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9675 - loss: 0.0923
Epoch 164/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9619 - loss: 0.0896
Epoch 165/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9604 - loss: 0.0990
Epoch 166/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9720 - loss: 0.0734
Epoch 167/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9665 - loss: 0.0928
Epoch 168/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9607 - loss: 0.0861
Epoch 169/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9726 - loss: 0.0812
Epoch 170/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9598 - loss: 0.0912
Epoch 171/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9664 - loss: 0.0881
Epoch 172/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9530 - loss: 0.1104
Epoch 173/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - BinaryAccuracy: 0.9660 - loss: 0.0798
Epoch 174/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9597 - loss: 0.1004
Epoch 175/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9573 - loss: 0.0973
Epoch 176/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9711 - loss: 0.0761
Epoch 177/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9622 - loss: 0.0989
Epoch 178/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - BinaryAccuracy: 0.9738 - loss: 0.0756
Epoch 179/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9663 - loss: 0.0903
Epoch 180/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9622 - loss: 0.0907
Epoch 181/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9785 - loss: 0.0744
Epoch 182/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9610 - loss: 0.1029
Epoch 183/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9771 - loss: 0.0777
Epoch 184/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9626 - loss: 0.0903
Epoch 185/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9743 - loss: 0.0789
Epoch 186/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9695 - loss: 0.0943
Epoch 187/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9592 - loss: 0.1027
Epoch 188/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9612 - loss: 0.0833
Epoch 189/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9691 - loss: 0.0925
Epoch 190/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9552 - loss: 0.0999
Epoch 191/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9614 - loss: 0.0806
Epoch 192/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9777 - loss: 0.0576
Epoch 193/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9602 - loss: 0.0861
Epoch 194/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9596 - loss: 0.0845
Epoch 195/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9653 - loss: 0.0922
Epoch 196/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9709 - loss: 0.0915
Epoch 197/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9599 - loss: 0.0920
Epoch 198/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9706 - loss: 0.0821
Epoch 199/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9632 - loss: 0.0900
Epoch 200/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9678 - loss: 0.0725
Epoch 201/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9705 - loss: 0.0730
Epoch 202/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9691 - loss: 0.0725
Epoch 203/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9700 - loss: 0.0780
Epoch 204/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9622 - loss: 0.0865
Epoch 205/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9688 - loss: 0.0915
Epoch 206/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9711 - loss: 0.0783
Epoch 207/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9644 - loss: 0.0931
Epoch 208/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9696 - loss: 0.0743
Epoch 209/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9706 - loss: 0.0700
Epoch 210/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9570 - loss: 0.0872
Epoch 211/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9724 - loss: 0.0770
Epoch 212/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9702 - loss: 0.0847
Epoch 213/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9646 - loss: 0.0770
Epoch 214/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9770 - loss: 0.0608
Epoch 215/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9750 - loss: 0.0811
Epoch 216/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9677 - loss: 0.0869
Epoch 217/250

In [21]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8909 - loss: 0.7145
Testing time: 0.27 seconds

In [22]:

y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
(378, 1)
(378,)

In [23]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8915343915343915
Confusion Matrix:
 [[309  17]
 [ 24  28]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94       326
           1       0.62      0.54      0.58        52

    accuracy                           0.89       378
   macro avg       0.78      0.74      0.76       378
weighted avg       0.89      0.89      0.89       378

In [24]:
# 3. We are using adagrad optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adagrad', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=250)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - BinaryAccuracy: 0.9678 - loss: 0.0736
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9845 - loss: 0.0469
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9833 - loss: 0.0563
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9802 - loss: 0.0573
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9788 - loss: 0.0559
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9888 - loss: 0.0457
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9851 - loss: 0.0477
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9764 - loss: 0.0599
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9874 - loss: 0.0461
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9848 - loss: 0.0459
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9830 - loss: 0.0454
Epoch 12/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9771 - loss: 0.0612
Epoch 13/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9840 - loss: 0.0454
Epoch 14/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9826 - loss: 0.0445
Epoch 15/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9776 - loss: 0.0511
Epoch 16/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9724 - loss: 0.0612
Epoch 17/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9820 - loss: 0.0620
Epoch 18/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9890 - loss: 0.0425
Epoch 19/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9821 - loss: 0.0543
Epoch 20/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9848 - loss: 0.0469
Epoch 21/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9870 - loss: 0.0437
Epoch 22/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9794 - loss: 0.0513
Epoch 23/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9788 - loss: 0.0526
Epoch 24/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9782 - loss: 0.0516
Epoch 25/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9844 - loss: 0.0464
Epoch 26/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9790 - loss: 0.0502
Epoch 27/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9889 - loss: 0.0404
Epoch 28/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9877 - loss: 0.0447
Epoch 29/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9689 - loss: 0.0688
Epoch 30/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9761 - loss: 0.0564
Epoch 31/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9840 - loss: 0.0488
Epoch 32/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9773 - loss: 0.0578
Epoch 33/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9835 - loss: 0.0490
Epoch 34/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9867 - loss: 0.0464
Epoch 35/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9791 - loss: 0.0531
Epoch 36/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9803 - loss: 0.0528
Epoch 37/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9879 - loss: 0.0422
Epoch 38/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9875 - loss: 0.0475
Epoch 39/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9863 - loss: 0.0442
Epoch 40/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9833 - loss: 0.0432
Epoch 41/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9852 - loss: 0.0476
Epoch 42/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9792 - loss: 0.0571
Epoch 43/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9841 - loss: 0.0420
Epoch 44/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9793 - loss: 0.0592
Epoch 45/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9847 - loss: 0.0445
Epoch 46/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9794 - loss: 0.0570
Epoch 47/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9800 - loss: 0.0501
Epoch 48/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9832 - loss: 0.0507
Epoch 49/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9839 - loss: 0.0528
Epoch 50/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9881 - loss: 0.0470
Epoch 51/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9880 - loss: 0.0448
Epoch 52/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9818 - loss: 0.0464
Epoch 53/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9888 - loss: 0.0412
Epoch 54/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9810 - loss: 0.0545
Epoch 55/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9816 - loss: 0.0619
Epoch 56/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9872 - loss: 0.0433
Epoch 57/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9840 - loss: 0.0468
Epoch 58/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9866 - loss: 0.0498
Epoch 59/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9832 - loss: 0.0494
Epoch 60/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9834 - loss: 0.0526
Epoch 61/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9864 - loss: 0.0479
Epoch 62/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9816 - loss: 0.0546
Epoch 63/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9803 - loss: 0.0535
Epoch 64/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9817 - loss: 0.0495
Epoch 65/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9806 - loss: 0.0546
Epoch 66/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9821 - loss: 0.0539
Epoch 67/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9850 - loss: 0.0466
Epoch 68/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9811 - loss: 0.0511
Epoch 69/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9887 - loss: 0.0459
Epoch 70/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9849 - loss: 0.0527
Epoch 71/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9813 - loss: 0.0549
Epoch 72/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9781 - loss: 0.0525
Epoch 73/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9838 - loss: 0.0452
Epoch 74/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9866 - loss: 0.0426
Epoch 75/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9886 - loss: 0.0479
Epoch 76/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9872 - loss: 0.0458
Epoch 77/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9878 - loss: 0.0444
Epoch 78/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9820 - loss: 0.0456
Epoch 79/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9840 - loss: 0.0515
Epoch 80/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9871 - loss: 0.0456
Epoch 81/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9779 - loss: 0.0533
Epoch 82/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9927 - loss: 0.0390
Epoch 83/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9907 - loss: 0.0361
Epoch 84/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9850 - loss: 0.0516
Epoch 85/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9811 - loss: 0.0515
Epoch 86/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9877 - loss: 0.0462
Epoch 87/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9879 - loss: 0.0494
Epoch 88/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9882 - loss: 0.0542
Epoch 89/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9873 - loss: 0.0399
Epoch 90/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9824 - loss: 0.0508
Epoch 91/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9800 - loss: 0.0519
Epoch 92/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9849 - loss: 0.0466
Epoch 93/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9881 - loss: 0.0372
Epoch 94/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9772 - loss: 0.0555
Epoch 95/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9810 - loss: 0.0551
Epoch 96/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9788 - loss: 0.0584
Epoch 97/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9841 - loss: 0.0484
Epoch 98/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9820 - loss: 0.0486
Epoch 99/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9805 - loss: 0.0505
Epoch 100/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9775 - loss: 0.0598
Epoch 101/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9838 - loss: 0.0544
Epoch 102/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9832 - loss: 0.0455
Epoch 103/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9832 - loss: 0.0495
Epoch 104/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9825 - loss: 0.0506
Epoch 105/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9772 - loss: 0.0550
Epoch 106/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9896 - loss: 0.0452
Epoch 107/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9859 - loss: 0.0522
Epoch 108/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9903 - loss: 0.0390
Epoch 109/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9798 - loss: 0.0508
Epoch 110/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9825 - loss: 0.0462
Epoch 111/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9855 - loss: 0.0546
Epoch 112/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9751 - loss: 0.0552
Epoch 113/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9813 - loss: 0.0551
Epoch 114/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9773 - loss: 0.0542
Epoch 115/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9744 - loss: 0.0598
Epoch 116/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9826 - loss: 0.0496
Epoch 117/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9904 - loss: 0.0386
Epoch 118/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9899 - loss: 0.0424
Epoch 119/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9866 - loss: 0.0436
Epoch 120/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9846 - loss: 0.0459
Epoch 121/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9856 - loss: 0.0469
Epoch 122/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9881 - loss: 0.0452
Epoch 123/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9859 - loss: 0.0471
Epoch 124/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9908 - loss: 0.0420
Epoch 125/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9885 - loss: 0.0405
Epoch 126/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9853 - loss: 0.0448
Epoch 127/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9869 - loss: 0.0453
Epoch 128/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9811 - loss: 0.0489
Epoch 129/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9879 - loss: 0.0427
Epoch 130/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9898 - loss: 0.0408
Epoch 131/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9773 - loss: 0.0600
Epoch 132/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9837 - loss: 0.0452
Epoch 133/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9870 - loss: 0.0456
Epoch 134/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9873 - loss: 0.0468
Epoch 135/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9812 - loss: 0.0455
Epoch 136/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9815 - loss: 0.0547
Epoch 137/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9809 - loss: 0.0505
Epoch 138/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9802 - loss: 0.0534
Epoch 139/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9857 - loss: 0.0469
Epoch 140/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9876 - loss: 0.0435
Epoch 141/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9820 - loss: 0.0483
Epoch 142/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9892 - loss: 0.0436
Epoch 143/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9786 - loss: 0.0543
Epoch 144/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9868 - loss: 0.0497
Epoch 145/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9764 - loss: 0.0539
Epoch 146/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9862 - loss: 0.0406
Epoch 147/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9814 - loss: 0.0539
Epoch 148/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9875 - loss: 0.0436
Epoch 149/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9826 - loss: 0.0505
Epoch 150/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9901 - loss: 0.0458
Epoch 151/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9742 - loss: 0.0562
Epoch 152/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9777 - loss: 0.0553
Epoch 153/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9847 - loss: 0.0482
Epoch 154/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9849 - loss: 0.0488
Epoch 155/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9850 - loss: 0.0467
Epoch 156/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9858 - loss: 0.0477
Epoch 157/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9795 - loss: 0.0510
Epoch 158/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9821 - loss: 0.0453
Epoch 159/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9853 - loss: 0.0415
Epoch 160/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9830 - loss: 0.0465
Epoch 161/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9834 - loss: 0.0507
Epoch 162/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9846 - loss: 0.0519
Epoch 163/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9856 - loss: 0.0487
Epoch 164/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9884 - loss: 0.0384
Epoch 165/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9899 - loss: 0.0391
Epoch 166/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9789 - loss: 0.0562
Epoch 167/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9870 - loss: 0.0402
Epoch 168/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9864 - loss: 0.0472
Epoch 169/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9912 - loss: 0.0393
Epoch 170/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9850 - loss: 0.0531
Epoch 171/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9853 - loss: 0.0450
Epoch 172/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9813 - loss: 0.0484
Epoch 173/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9874 - loss: 0.0407
Epoch 174/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9811 - loss: 0.0513
Epoch 175/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9673 - loss: 0.0698
Epoch 176/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9829 - loss: 0.0523
Epoch 177/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9874 - loss: 0.0418
Epoch 178/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9792 - loss: 0.0506
Epoch 179/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9858 - loss: 0.0476
Epoch 180/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9898 - loss: 0.0364
Epoch 181/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9866 - loss: 0.0421
Epoch 182/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9900 - loss: 0.0421
Epoch 183/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9804 - loss: 0.0530
Epoch 184/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9818 - loss: 0.0425
Epoch 185/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9901 - loss: 0.0449
Epoch 186/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9842 - loss: 0.0527
Epoch 187/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9892 - loss: 0.0389
Epoch 188/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9836 - loss: 0.0508
Epoch 189/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9844 - loss: 0.0473
Epoch 190/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9787 - loss: 0.0556
Epoch 191/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9894 - loss: 0.0387
Epoch 192/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9854 - loss: 0.0428
Epoch 193/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9820 - loss: 0.0480
Epoch 194/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9793 - loss: 0.0485
Epoch 195/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9810 - loss: 0.0508
Epoch 196/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9880 - loss: 0.0420
Epoch 197/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9838 - loss: 0.0464
Epoch 198/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9838 - loss: 0.0509
Epoch 199/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9874 - loss: 0.0431
Epoch 200/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9822 - loss: 0.0462
Epoch 201/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9860 - loss: 0.0448
Epoch 202/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9847 - loss: 0.0473
Epoch 203/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9809 - loss: 0.0521
Epoch 204/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9806 - loss: 0.0476
Epoch 205/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9799 - loss: 0.0543
Epoch 206/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9782 - loss: 0.0551
Epoch 207/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9842 - loss: 0.0471
Epoch 208/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9819 - loss: 0.0517
Epoch 209/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9871 - loss: 0.0449
Epoch 210/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9794 - loss: 0.0577
Epoch 211/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9734 - loss: 0.0578
Epoch 212/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9870 - loss: 0.0442
Epoch 213/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9879 - loss: 0.0433
Epoch 214/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9855 - loss: 0.0460
Epoch 215/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9844 - loss: 0.0494
Epoch 216/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9899 - loss: 0.0433
Epoch 217/250

In [25]:

start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8872 - loss: 0.7351
Testing time: 0.41 seconds

In [26]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
(378, 1)
(378,)

In [27]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8888888888888888
Confusion Matrix:
 [[309  17]
 [ 25  27]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94       326
           1       0.61      0.52      0.56        52

    accuracy                           0.89       378
   macro avg       0.77      0.73      0.75       378
weighted avg       0.88      0.89      0.88       378