<a href="https://colab.research.google.com/github/Hemant10HM/ANNDL-LAB_24mcs004/blob/main/ANN_LAB_3_MLP_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [2]:
# Define dataset path
dataset_path = "/content/drive/MyDrive/data/WineQT.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.drop('Id', axis=1, inplace=True)

In [4]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
# Craeting binary classification target
df['Good'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [7]:
X = df.drop(['quality', 'Good'], axis=1)

In [8]:
# Scale features
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [9]:
# Round scaled features
X_scaled = X_scaled.round(2)

In [10]:

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [12]:
X_bin = X_scaled.copy()
y_bin = df['Good']

In [13]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X_bin,y_bin,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (765, 11)
X_test shape :  (378, 11)
y_train shape :  (765,)
y_test shape :  (378,)

In [14]:

# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 11))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [15]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])
history = model.fit(X_train, y_train, epochs=250)

Epoch 1/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - BinaryAccuracy: 0.8634 - loss: 0.5888
Epoch 2/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8820 - loss: 0.4167
Epoch 3/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8728 - loss: 0.3642
Epoch 4/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8433 - loss: 0.3980
Epoch 5/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8510 - loss: 0.3625
Epoch 6/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8387 - loss: 0.3690
Epoch 7/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8447 - loss: 0.3313
Epoch 8/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8343 - loss: 0.3540
Epoch 9/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8766 - loss: 0.2882
Epoch 10/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8607 - loss: 0.2760
Epoch 11/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8791 - loss: 0.2832
Epoch 12/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8556 - loss: 0.3022
Epoch 13/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8682 - loss: 0.2913
Epoch 14/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8826 - loss: 0.2798
Epoch 15/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8764 - loss: 0.2776
Epoch 16/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8647 - loss: 0.2832
Epoch 17/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8571 - loss: 0.3033
Epoch 18/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8705 - loss: 0.2920
Epoch 19/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8805 - loss: 0.2680
Epoch 20/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8660 - loss: 0.2813
Epoch 21/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8821 - loss: 0.2745
Epoch 22/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8578 - loss: 0.2927
Epoch 23/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8929 - loss: 0.2583
Epoch 24/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8700 - loss: 0.2800
Epoch 25/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8643 - loss: 0.2996
Epoch 26/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8763 - loss: 0.2648
Epoch 27/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8751 - loss: 0.2776
Epoch 28/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8917 - loss: 0.2441
Epoch 29/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8889 - loss: 0.2556
Epoch 30/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8897 - loss: 0.2588
Epoch 31/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8907 - loss: 0.2636
Epoch 32/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8885 - loss: 0.2386
Epoch 33/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8806 - loss: 0.2732
Epoch 34/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8612 - loss: 0.2812
Epoch 35/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8561 - loss: 0.2925
Epoch 36/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8792 - loss: 0.2758
Epoch 37/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8804 - loss: 0.2599
Epoch 38/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8846 - loss: 0.2804
Epoch 39/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8718 - loss: 0.2991
Epoch 40/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8884 - loss: 0.2660
Epoch 41/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9115 - loss: 0.2320
Epoch 42/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8772 - loss: 0.2715
Epoch 43/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8981 - loss: 0.2507
Epoch 44/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8782 - loss: 0.2604
Epoch 45/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8851 - loss: 0.2662
Epoch 46/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8794 - loss: 0.2682
Epoch 47/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8814 - loss: 0.2861
Epoch 48/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8899 - loss: 0.2494
Epoch 49/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8814 - loss: 0.2502
Epoch 50/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8711 - loss: 0.2926
Epoch 51/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8833 - loss: 0.2809
Epoch 52/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8953 - loss: 0.2485
Epoch 53/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8846 - loss: 0.2420
Epoch 54/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8870 - loss: 0.2572
Epoch 55/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8815 - loss: 0.2430
Epoch 56/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8896 - loss: 0.2351
Epoch 57/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8864 - loss: 0.2534
Epoch 58/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8806 - loss: 0.2711
Epoch 59/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.8900 - loss: 0.2666
Epoch 60/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9082 - loss: 0.2287
Epoch 61/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8936 - loss: 0.2669
Epoch 62/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8880 - loss: 0.2489
Epoch 63/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8887 - loss: 0.2462
Epoch 64/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8808 - loss: 0.2555
Epoch 65/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8753 - loss: 0.2552
Epoch 66/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9155 - loss: 0.2183
Epoch 67/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8799 - loss: 0.2414
Epoch 68/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8887 - loss: 0.2427
Epoch 69/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8739 - loss: 0.2697
Epoch 70/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8979 - loss: 0.2463
Epoch 71/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8793 - loss: 0.2475
Epoch 72/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8870 - loss: 0.2415
Epoch 73/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8834 - loss: 0.2445
Epoch 74/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8894 - loss: 0.2572
Epoch 75/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8931 - loss: 0.2643
Epoch 76/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9060 - loss: 0.2535
Epoch 77/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8997 - loss: 0.2461
Epoch 78/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8693 - loss: 0.2753
Epoch 79/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8947 - loss: 0.2274
Epoch 80/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8821 - loss: 0.2570
Epoch 81/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8814 - loss: 0.2455
Epoch 82/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8909 - loss: 0.2453
Epoch 83/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.8935 - loss: 0.2434
Epoch 84/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8916 - loss: 0.2426
Epoch 85/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8934 - loss: 0.2390
Epoch 86/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9072 - loss: 0.2185
Epoch 87/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9104 - loss: 0.2157
Epoch 88/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8990 - loss: 0.2500
Epoch 89/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8927 - loss: 0.2542
Epoch 90/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8967 - loss: 0.2459
Epoch 91/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9034 - loss: 0.2417
Epoch 92/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8849 - loss: 0.2695
Epoch 93/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9043 - loss: 0.2205
Epoch 94/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8786 - loss: 0.2550
Epoch 95/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8984 - loss: 0.2430
Epoch 96/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8932 - loss: 0.2274
Epoch 97/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9212 - loss: 0.2009
Epoch 98/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9003 - loss: 0.2361
Epoch 99/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8976 - loss: 0.2179
Epoch 100/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9040 - loss: 0.2289
Epoch 101/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8961 - loss: 0.2279
Epoch 102/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8879 - loss: 0.2297
Epoch 103/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9028 - loss: 0.2136
Epoch 104/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9028 - loss: 0.2275
Epoch 105/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.8905 - loss: 0.2494
Epoch 106/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9073 - loss: 0.2172
Epoch 107/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9107 - loss: 0.2241
Epoch 108/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9013 - loss: 0.2250
Epoch 109/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9105 - loss: 0.2020
Epoch 110/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9180 - loss: 0.2160
Epoch 111/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9064 - loss: 0.2193
Epoch 112/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9042 - loss: 0.2083
Epoch 113/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9105 - loss: 0.2235
Epoch 114/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9097 - loss: 0.2102
Epoch 115/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9103 - loss: 0.2235
Epoch 116/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9134 - loss: 0.2304
Epoch 117/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9141 - loss: 0.2023
Epoch 118/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9233 - loss: 0.2007
Epoch 119/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9170 - loss: 0.2106
Epoch 120/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9067 - loss: 0.2359
Epoch 121/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9321 - loss: 0.1829
Epoch 122/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9078 - loss: 0.2177
Epoch 123/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9220 - loss: 0.2153
Epoch 124/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9137 - loss: 0.2342
Epoch 125/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9194 - loss: 0.1974
Epoch 126/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9271 - loss: 0.1910
Epoch 127/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9149 - loss: 0.2253
Epoch 128/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9199 - loss: 0.2057
Epoch 129/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9114 - loss: 0.2159
Epoch 130/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9224 - loss: 0.1916
Epoch 131/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9112 - loss: 0.2227
Epoch 132/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9071 - loss: 0.2269
Epoch 133/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9162 - loss: 0.2254
Epoch 134/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9268 - loss: 0.2118
Epoch 135/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9229 - loss: 0.2216
Epoch 136/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9140 - loss: 0.2163
Epoch 137/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9377 - loss: 0.1827
Epoch 138/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9151 - loss: 0.2093
Epoch 139/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9155 - loss: 0.2189
Epoch 140/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9105 - loss: 0.2195
Epoch 141/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9305 - loss: 0.1922
Epoch 142/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9226 - loss: 0.1969
Epoch 143/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9362 - loss: 0.1826
Epoch 144/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9090 - loss: 0.2230
Epoch 145/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9131 - loss: 0.1915
Epoch 146/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9301 - loss: 0.1796
Epoch 147/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9244 - loss: 0.2007
Epoch 148/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9289 - loss: 0.2012
Epoch 149/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9209 - loss: 0.1966
Epoch 150/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9134 - loss: 0.2060
Epoch 151/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9251 - loss: 0.1811
Epoch 152/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9375 - loss: 0.1885
Epoch 153/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9011 - loss: 0.2169
Epoch 154/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9232 - loss: 0.2019
Epoch 155/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9098 - loss: 0.2213
Epoch 156/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9265 - loss: 0.1828
Epoch 157/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9426 - loss: 0.1897
Epoch 158/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9331 - loss: 0.1857
Epoch 159/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9183 - loss: 0.2134
Epoch 160/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9308 - loss: 0.1903
Epoch 161/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9419 - loss: 0.1734
Epoch 162/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9323 - loss: 0.1778
Epoch 163/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9310 - loss: 0.1799
Epoch 164/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9463 - loss: 0.1594
Epoch 165/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9320 - loss: 0.1846
Epoch 166/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9326 - loss: 0.1763
Epoch 167/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9320 - loss: 0.1853
Epoch 168/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9309 - loss: 0.1837
Epoch 169/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9251 - loss: 0.1871
Epoch 170/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9124 - loss: 0.2066
Epoch 171/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9341 - loss: 0.1739
Epoch 172/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9258 - loss: 0.1776
Epoch 173/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9349 - loss: 0.1975
Epoch 174/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9167 - loss: 0.1963
Epoch 175/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9339 - loss: 0.1674
Epoch 176/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9244 - loss: 0.1948
Epoch 177/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9188 - loss: 0.1721
Epoch 178/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9175 - loss: 0.1944
Epoch 179/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9327 - loss: 0.1851
Epoch 180/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9142 - loss: 0.2061
Epoch 181/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9267 - loss: 0.1880
Epoch 182/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9323 - loss: 0.1833
Epoch 183/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9429 - loss: 0.1747
Epoch 184/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9321 - loss: 0.1802
Epoch 185/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9443 - loss: 0.1746
Epoch 186/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9333 - loss: 0.1791
Epoch 187/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9442 - loss: 0.1687
Epoch 188/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9413 - loss: 0.1657
Epoch 189/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9052 - loss: 0.1997
Epoch 190/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9228 - loss: 0.1961
Epoch 191/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9174 - loss: 0.1920
Epoch 192/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9193 - loss: 0.2035
Epoch 193/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9126 - loss: 0.1835
Epoch 194/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9211 - loss: 0.1933
Epoch 195/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9417 - loss: 0.1821
Epoch 196/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9355 - loss: 0.1716
Epoch 197/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9148 - loss: 0.1961
Epoch 198/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9304 - loss: 0.1698
Epoch 199/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9409 - loss: 0.1574
Epoch 200/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9365 - loss: 0.1625
Epoch 201/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9472 - loss: 0.1543
Epoch 202/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9383 - loss: 0.1563
Epoch 203/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9405 - loss: 0.1741
Epoch 204/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9320 - loss: 0.1737
Epoch 205/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9398 - loss: 0.1668
Epoch 206/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9339 - loss: 0.1836
Epoch 207/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9306 - loss: 0.1786
Epoch 208/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9460 - loss: 0.1559
Epoch 209/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9503 - loss: 0.1549
Epoch 210/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9202 - loss: 0.1836
Epoch 211/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9360 - loss: 0.1496
Epoch 212/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9347 - loss: 0.1697
Epoch 213/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9329 - loss: 0.1609
Epoch 214/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9473 - loss: 0.1486
Epoch 215/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9309 - loss: 0.1707
Epoch 216/250
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9395 - loss: 0.1492
Epoch 217/250

In [16]:

y_pred = model.predict(X_test)
y_pred.shape

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

(378, 1)

In [17]:

y_bi_pred = (y_pred > 0.5).astype(int).flatten()
y_bi_pred.shape

(378,)

In [18]:

# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8756613756613757
Confusion Matrix:
 [[308  18]
 [ 29  23]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.94      0.93       326
           1       0.56      0.44      0.49        52

    accuracy                           0.88       378
   macro avg       0.74      0.69      0.71       378
weighted avg       0.87      0.88      0.87       378

In [19]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Good
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [20]:
#Multiclass now
X_multi = X_scaled.copy()
y_multi = df['quality']

In [30]:
y_shifted = y_multi - y_multi.min()
num_classes = len(np.unique(y_shifted))

# One-hot encode target labels
y_encoded = to_categorical(y_shifted, num_classes=num_classes)

In [42]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_multi, y_encoded, test_size=0.2, random_state=42, stratify=y_shifted)

In [43]:
print("X_Train Shape : ",X_train.shape)
print("X_Test Shape : ",X_test.shape)
print("y_train Shape : ",y_train.shape)
print("y_test Shape : ",y_test.shape)

X_Train Shape :  (914, 11)
X_Test Shape :  (229, 11)
y_train Shape :  (914, 6)
y_test Shape :  (229, 6)

In [44]:
# Build the MLP Model
model = tf.keras.Sequential()

# Model :
model.add(tf.keras.layers.Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

# Compile the Model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the Model
history = model.fit(X_train, y_train, epochs=250)

Epoch 1/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4380 - loss: 1.6588
Epoch 2/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4453 - loss: 1.2097
Epoch 3/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5102 - loss: 1.1487
Epoch 4/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5354 - loss: 1.1238
Epoch 5/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5666 - loss: 1.0520
Epoch 6/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5692 - loss: 0.9884
Epoch 7/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5744 - loss: 1.0356
Epoch 8/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5699 - loss: 0.9965
Epoch 9/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6052 - loss: 0.9643
Epoch 10/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5915 - loss: 0.9585
Epoch 11/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6246 - loss: 0.9613
Epoch 12/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5687 - loss: 0.9882
Epoch 13/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6339 - loss: 0.9198
Epoch 14/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5843 - loss: 0.9553
Epoch 15/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6093 - loss: 0.9205
Epoch 16/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6354 - loss: 0.9222
Epoch 17/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6449 - loss: 0.8977
Epoch 18/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6057 - loss: 0.9432
Epoch 19/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6192 - loss: 0.9458
Epoch 20/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5936 - loss: 0.9166
Epoch 21/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.8923
Epoch 22/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6498 - loss: 0.8658
Epoch 23/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6333 - loss: 0.9076
Epoch 24/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6287 - loss: 0.9082
Epoch 25/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6320 - loss: 0.9057
Epoch 26/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.9280
Epoch 27/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6107 - loss: 0.9304
Epoch 28/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.8964
Epoch 29/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6335 - loss: 0.8713
Epoch 30/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6280 - loss: 0.8771
Epoch 31/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6251 - loss: 0.8746
Epoch 32/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6227 - loss: 0.8876
Epoch 33/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6335 - loss: 0.8855
Epoch 34/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6251 - loss: 0.8760
Epoch 35/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6430 - loss: 0.8753
Epoch 36/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6099 - loss: 0.9092
Epoch 37/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6041 - loss: 0.8952
Epoch 38/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6104 - loss: 0.8944
Epoch 39/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6465 - loss: 0.8548
Epoch 40/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6215 - loss: 0.8742
Epoch 41/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6704 - loss: 0.8288
Epoch 42/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6401 - loss: 0.8574
Epoch 43/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.8522
Epoch 44/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6399 - loss: 0.8599
Epoch 45/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6632 - loss: 0.8366
Epoch 46/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6287 - loss: 0.8693
Epoch 47/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6337 - loss: 0.8699
Epoch 48/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6462 - loss: 0.8505
Epoch 49/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.8575
Epoch 50/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6589 - loss: 0.8413
Epoch 51/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6541 - loss: 0.8289
Epoch 52/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6231 - loss: 0.8604
Epoch 53/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6396 - loss: 0.8566
Epoch 54/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6561 - loss: 0.8418
Epoch 55/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6327 - loss: 0.9023
Epoch 56/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6558 - loss: 0.8275
Epoch 57/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6434 - loss: 0.8476
Epoch 58/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6588 - loss: 0.8306
Epoch 59/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6788 - loss: 0.8122
Epoch 60/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6566 - loss: 0.8348
Epoch 61/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6622 - loss: 0.8179
Epoch 62/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6733 - loss: 0.8159
Epoch 63/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6702 - loss: 0.8036
Epoch 64/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6322 - loss: 0.8220
Epoch 65/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6536 - loss: 0.8269
Epoch 66/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6455 - loss: 0.8512
Epoch 67/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6304 - loss: 0.8088
Epoch 68/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6352 - loss: 0.8227
Epoch 69/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6794 - loss: 0.7981
Epoch 70/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6599 - loss: 0.8020
Epoch 71/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6445 - loss: 0.8348
Epoch 72/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6738 - loss: 0.7923
Epoch 73/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6553 - loss: 0.7937
Epoch 74/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6394 - loss: 0.8005
Epoch 75/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6672 - loss: 0.7963
Epoch 76/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6755 - loss: 0.7652
Epoch 77/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6779 - loss: 0.8094
Epoch 78/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6761 - loss: 0.7730
Epoch 79/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6797 - loss: 0.7646
Epoch 80/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6756 - loss: 0.7675
Epoch 81/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6792 - loss: 0.7688
Epoch 82/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6281 - loss: 0.8232
Epoch 83/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6694 - loss: 0.7528
Epoch 84/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6458 - loss: 0.7855
Epoch 85/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6804 - loss: 0.7543
Epoch 86/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6833 - loss: 0.7646
Epoch 87/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6415 - loss: 0.8239
Epoch 88/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6696 - loss: 0.8022
Epoch 89/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6723 - loss: 0.7906
Epoch 90/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6608 - loss: 0.7603
Epoch 91/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6604 - loss: 0.7963
Epoch 92/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6779 - loss: 0.7588
Epoch 93/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6631 - loss: 0.7855
Epoch 94/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6953 - loss: 0.7662
Epoch 95/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6685 - loss: 0.7863
Epoch 96/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6725 - loss: 0.7550
Epoch 97/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6966 - loss: 0.7340
Epoch 98/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6885 - loss: 0.7444
Epoch 99/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6869 - loss: 0.7642
Epoch 100/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6822 - loss: 0.7481
Epoch 101/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6888 - loss: 0.7400
Epoch 102/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6793 - loss: 0.7752
Epoch 103/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6834 - loss: 0.7558
Epoch 104/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7058 - loss: 0.7192
Epoch 105/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6938 - loss: 0.7428
Epoch 106/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6799 - loss: 0.7532
Epoch 107/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6703 - loss: 0.7646
Epoch 108/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6876 - loss: 0.7359
Epoch 109/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7062 - loss: 0.7473
Epoch 110/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7041 - loss: 0.7414
Epoch 111/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6954 - loss: 0.7345
Epoch 112/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6878 - loss: 0.7713
Epoch 113/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7107 - loss: 0.6971
Epoch 114/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7146 - loss: 0.6911
Epoch 115/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6702 - loss: 0.7465
Epoch 116/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7072 - loss: 0.6959
Epoch 117/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6928 - loss: 0.7101
Epoch 118/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7132 - loss: 0.7182
Epoch 119/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6849 - loss: 0.7389
Epoch 120/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7180 - loss: 0.7120
Epoch 121/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7119 - loss: 0.6871
Epoch 122/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7094 - loss: 0.7105
Epoch 123/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7062 - loss: 0.7075
Epoch 124/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7082 - loss: 0.6806
Epoch 125/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7166 - loss: 0.7113
Epoch 126/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7107 - loss: 0.7004
Epoch 127/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6987 - loss: 0.7218
Epoch 128/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7027 - loss: 0.7060
Epoch 129/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6852 - loss: 0.7474
Epoch 130/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7055 - loss: 0.7087
Epoch 131/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7052 - loss: 0.7258
Epoch 132/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6797 - loss: 0.7301
Epoch 133/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7201 - loss: 0.6912
Epoch 134/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6922 - loss: 0.7210
Epoch 135/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.6840
Epoch 136/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7142 - loss: 0.6886
Epoch 137/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7047 - loss: 0.6736
Epoch 138/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7055 - loss: 0.6958
Epoch 139/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7193 - loss: 0.7034
Epoch 140/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6922 - loss: 0.6908
Epoch 141/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7130 - loss: 0.6868
Epoch 142/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6943 - loss: 0.7072
Epoch 143/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6944 - loss: 0.6807
Epoch 144/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7278 - loss: 0.6578
Epoch 145/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7106 - loss: 0.6740
Epoch 146/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7373 - loss: 0.6593
Epoch 147/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7126 - loss: 0.6725
Epoch 148/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7066 - loss: 0.6585
Epoch 149/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7256 - loss: 0.6547
Epoch 150/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.6785
Epoch 151/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7155 - loss: 0.7078
Epoch 152/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7148 - loss: 0.6695
Epoch 153/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7262 - loss: 0.6322
Epoch 154/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7250 - loss: 0.6510
Epoch 155/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7274 - loss: 0.6282
Epoch 156/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7196 - loss: 0.6545
Epoch 157/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.6538
Epoch 158/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7336 - loss: 0.6348
Epoch 159/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7357 - loss: 0.6492
Epoch 160/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7456 - loss: 0.6437
Epoch 161/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7210 - loss: 0.6598
Epoch 162/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7306 - loss: 0.6461
Epoch 163/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7172 - loss: 0.6533
Epoch 164/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7285 - loss: 0.6258
Epoch 165/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7009 - loss: 0.6540
Epoch 166/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7158 - loss: 0.6367
Epoch 167/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7334 - loss: 0.6181
Epoch 168/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7495 - loss: 0.6160
Epoch 169/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7554 - loss: 0.6209
Epoch 170/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7283 - loss: 0.6456
Epoch 171/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7253 - loss: 0.6407
Epoch 172/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7320 - loss: 0.6154
Epoch 173/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7366 - loss: 0.6236
Epoch 174/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7410 - loss: 0.6112
Epoch 175/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7338 - loss: 0.6211
Epoch 176/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7211 - loss: 0.6033
Epoch 177/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7364 - loss: 0.6345
Epoch 178/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7570 - loss: 0.5861
Epoch 179/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7462 - loss: 0.6081
Epoch 180/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7177 - loss: 0.6196
Epoch 181/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7242 - loss: 0.6348
Epoch 182/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7368 - loss: 0.6202
Epoch 183/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7319 - loss: 0.6239
Epoch 184/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7580 - loss: 0.5996
Epoch 185/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7517 - loss: 0.5898
Epoch 186/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7578 - loss: 0.5917
Epoch 187/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7268 - loss: 0.6439
Epoch 188/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7400 - loss: 0.6184
Epoch 189/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7577 - loss: 0.5678
Epoch 190/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7716 - loss: 0.5869
Epoch 191/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7530 - loss: 0.5785
Epoch 192/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7746 - loss: 0.5673
Epoch 193/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7700 - loss: 0.5718
Epoch 194/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7742 - loss: 0.5819
Epoch 195/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7272 - loss: 0.6256
Epoch 196/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7579 - loss: 0.5912
Epoch 197/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7579 - loss: 0.5723
Epoch 198/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7770 - loss: 0.5556
Epoch 199/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7669 - loss: 0.5994
Epoch 200/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7740 - loss: 0.5605
Epoch 201/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7728 - loss: 0.5527
Epoch 202/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7547 - loss: 0.5746
Epoch 203/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7570 - loss: 0.5647
Epoch 204/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7553 - loss: 0.5840
Epoch 205/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7719 - loss: 0.5838
Epoch 206/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7518 - loss: 0.5933
Epoch 207/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7565 - loss: 0.6147
Epoch 208/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7956 - loss: 0.5218
Epoch 209/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7666 - loss: 0.5926
Epoch 210/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7703 - loss: 0.5789
Epoch 211/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7742 - loss: 0.5608
Epoch 212/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7787 - loss: 0.5535
Epoch 213/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7682 - loss: 0.5599
Epoch 214/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7606 - loss: 0.5500
Epoch 215/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7821 - loss: 0.5408
Epoch 216/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7615 - loss: 0.5911
Epoch 217/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7949 - loss: 0.5414
Epoch 218/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7461 - loss: 0.5777
Epoch 219/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5299
Epoch 220/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7652 - loss: 0.5799
Epoch 221/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7854 - loss: 0.5394
Epoch 222/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7833 - loss: 0.5323
Epoch 223/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7870 - loss: 0.5476
Epoch 224/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7698 - loss: 0.5593
Epoch 225/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7808 - loss: 0.5455
Epoch 226/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7446 - loss: 0.5947
Epoch 227/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7924 - loss: 0.5279
Epoch 228/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7702 - loss: 0.5567
Epoch 229/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7912 - loss: 0.5561
Epoch 230/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7768 - loss: 0.5255
Epoch 231/250
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8080 - loss: 0.5064

In [45]:
pred_probs = model.predict(X_test)
pred_classes = np.argmax(pred_probs, axis=1)
original_preds = pred_classes + y_multi.min()  # Add the offset back

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

In [46]:
# Also shift y_test back to original labels
y_test_original = np.argmax(y_test, axis=1) + y_multi.min()

# Accuracy
accuracy = accuracy_score(y_test_original, original_preds)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test_original, original_preds)

# Classification Report
class_report = classification_report(y_test_original, original_preds)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6506550218340611
Confusion Matrix:
 [[ 0  0  1  0  0  0]
 [ 0  1  3  3  0  0]
 [ 0  1 70 25  1  0]
 [ 0  1 20 63  8  0]
 [ 0  0  3  9 15  2]
 [ 0  0  0  1  2  0]]
Classification Report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.33      0.14      0.20         7
           5       0.72      0.72      0.72        97
           6       0.62      0.68      0.65        92
           7       0.58      0.52      0.55        29
           8       0.00      0.00      0.00         3

    accuracy                           0.65       229
   macro avg       0.38      0.34      0.35       229
weighted avg       0.64      0.65      0.64       229